#!/usr/bin/env node
/**
 * Locale audit → Discord embed payload.
 *
 * Parses LocaleBase.lua and each locale file, generates a Discord webhook
 * JSON payload with an embed showing translation coverage.
 *
 * Outputs JSON to stdout. Used by CI (.gitlab-ci.yml locale-audit job).
 *
 * Usage: node tools/locale_audit_discord.js
 */

const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const LOCALES_DIR = path.join(ROOT, 'locales');

const LOCALES = [
    { code: 'deDE', flag: '\uD83C\uDDE9\uD83C\uDDEA', name: 'German' },
    { code: 'zhCN', flag: '\uD83C\uDDE8\uD83C\uDDF3', name: 'Chinese' },
    { code: 'ptBR', flag: '\uD83C\uDDE7\uD83C\uDDF7', name: 'Portuguese' },
    { code: 'frFR', flag: '\uD83C\uDDEB\uD83C\uDDF7', name: 'French' },
    { code: 'koKR', flag: '\uD83C\uDDF0\uD83C\uDDF7', name: 'Korean' },
    { code: 'ruRU', flag: '\uD83C\uDDF7\uD83C\uDDFA', name: 'Russian' },
    { code: 'esES', flag: '\uD83C\uDDEA\uD83C\uDDF8', name: 'Spanish' },
];

// ── Parse keys ────────────────────────────────────────────────────────

function parseKeys(filePath) {
    const src = fs.readFileSync(filePath, 'utf8');
    const keys = new Set();
    for (const line of src.split(/\r?\n/)) {
        const m = line.match(/^L\["(.+?)"\]\s*=/);
        if (m) keys.add(m[1]);
    }
    return keys;
}

// ── Progress bar ──────────────────────────────────────────────────────

function progressBar(pct, len) {
    const filled = Math.round(pct / 100 * len);
    return '\u2588'.repeat(filled) + '\u2591'.repeat(len - filled);
}

// ── Main ──────────────────────────────────────────────────────────────

const baseKeys = parseKeys(path.join(LOCALES_DIR, 'LocaleBase.lua'));
const total = baseKeys.size;

const lines = [];
lines.push('```');
lines.push(`${'Language'.padEnd(22)} Coverage`);
lines.push('-'.repeat(38));

for (const locale of LOCALES) {
    const filePath = path.join(LOCALES_DIR, `${locale.code}.lua`);
    let translated = 0;
    if (fs.existsSync(filePath)) {
        const localeKeys = parseKeys(filePath);
        translated = [...baseKeys].filter(k => localeKeys.has(k)).length;
    }
    const pct = Math.round(translated / total * 100);
    const bar = progressBar(pct, 11);
    lines.push(`${(locale.name + ' (' + locale.code + ')').padEnd(22)} ${bar}  ${pct}%`);
}

lines.push('```');

const description = [
    `Translation coverage across **${total} strings**:\n`,
    lines.join('\n'),
    '',
    '**Want to help translate?**',
    '1. Download the template: [locale_template.lua](https://gitlab.com/Crystilac/horizon-suite/-/blob/main/locales/locale_template.lua)',
    '2. Copy, rename to your locale (e.g. `itIT.lua`), translate values',
    '3. Post your file in <#localisation-submission> for review!',
].join('\n');

const payload = {
    username: 'Locale Audit',
    embeds: [{
        title: 'Horizon Suite \u2014 Translation Coverage',
        description: description,
        color: 0x00CCFF,
        footer: { text: 'Auto-generated by CI \u2022 Updates on schedule' },
        timestamp: new Date().toISOString(),
    }],
};

process.stdout.write(JSON.stringify(payload, null, 2) + '\n');
