name: Package and release

on:
  push:
    tags:
      - "**"

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Clone project
        uses: actions/checkout@v6

      - name: Install Subversion
        run: |
          sudo apt-get update
          sudo apt-get install -y subversion

      - name: Package and release
        uses: BigWigsMods/packager@v2
